name: CI Workflow
description: This workflow runs tests on every push or pull request to the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo, pdo_pgsql
          coverage: none

      - name: Setup environment variables
        run: |
          echo "POSTGRES_USER=test_user" >> .env
          echo "POSTGRES_PASSWORD=test_pass" >> .env
          echo "POSTGRES_DB=test_db" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "TOKEN=test_token" >> .env

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --no-progress --no-interaction

      - name: Start application server
        run: |
          docker compose up -d --build --wait

      - name: Check server health
        run: |
          curl -I http://localhost:9000 || true
          docker ps
          docker logs $(docker ps -q --filter name=server)

      - name: Run PHPUnit tests
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
          REDIS_HOST: redis
          REDIS_PORT: 6379
          TOKEN: test_token
        run: docker compose exec server ./vendor/bin/phpunit tests

      - name: Stop containers
        if: always()
        run: docker compose down